# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RadioSpirit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RadioSpirit
  pod 'IQKeyboardManager'

  pod 'Firebase/Core'

end
